---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgdockertest
  namespace: dory
data:
  entrypoint.sh: |-
    #!/bin/bash
    apt-get -y update
    apt-get -y install curl ca-certificates gnupg
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    apt -y install lsb-core
    sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    apt-get update
    apt -y install postgresql-client-11
---
apiVersion: v1
kind: Pod
metadata:
  name: pgdockertest
  namespace: dory
spec:
  containers:
  - name: ubuntu
    image: "ubuntu:18.04"
    command:
    - /bin/entrypoint.sh
    volumeMounts:
    - name: configmap-volume
      mountPath: /bin/entrypoint.sh
      readOnly: true
      subPath: entrypoint.sh
  volumes:
  - name: configmap-volume
    configMap:
      defaultMode: 0700
      name: pgdockertest
